services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ai_optimization_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-aioptimization}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aioptimization}
      POSTGRES_DB: ${POSTGRES_DB:-aioptimization}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-aioptimization}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ai_optimization_network
