[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "python -m uvicorn api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
restartPolicyType = "always"
healthcheckTimeout = 300

# This will deploy just the backend first
# After backend is working, you can add frontend services
