[build]
builder = "dockerfile"
dockerfilePath = "./backend/Dockerfile"

[deploy]
startCommand = "uvicorn api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
restartPolicyType = "always"

[[volumes]]
name = "postgres_data"
mountPath = "/var/lib/postgresql/data"

[[volumes]]
name = "redis_data"
mountPath = "/data"
