[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "sh /app/entrypoint.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
# Install only prod deps at build; optionally install dev deps post-deploy via entrypoint
INSTALL_DEV_DEPS = "false"
PORT = "8000"
PYTHONPATH = "/app"
