[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile.frontend"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
PORT = "3000"
NODE_ENV = "production"
VITE_GOOGLE_CLIENT_ID = "${{VITE_GOOGLE_CLIENT_ID}}"
VITE_API_URL = "${{VITE_API_URL}}"
VITE_ENVIRONMENT = "${{VITE_ENVIRONMENT}}"

