[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.postgres"

[deploy]
startCommand = "sh -lc \"docker-entrypoint.sh postgres -p $PORT\""
restartPolicyType = "always"
healthcheckPath = "/" # not used; health via container healthcheck

[variables]
POSTGRES_DB = "aioptimization"
POSTGRES_USER = "aioptimization"
POSTGRES_PASSWORD = "aioptimization"
