[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.postgres"

[deploy]
startCommand = "sh -lc \"/usr/local/bin/postgres-entrypoint.sh\""
restartPolicyType = "always"
healthcheckPath = "/" # not used; health via container healthcheck

[variables]
POSTGRES_DB = "aioptimization"
POSTGRES_USER = "aioptimization"
POSTGRES_PASSWORD = "aioptimization"
